### ISSUE TITLE
Parsons (pp2_10_1) might benefit from more scaffolding

### ISSUE THREAD

**Issue by pearcej** [celinelatulipe/ThinkLikeComputer#73]
Parsons (pp2_10_1) has a lot going on in it! Students need to understand order of operations as well as parsing, and even though there is quite a lot of explanation, I suspect my students will find it confusing as is. 

I think it would benefit from the addition of two things before it:
1. Text that describes when a function object is "looked up" because it might be when it is first scanned or just before it is actually used.
2. A much smaller example that has far fewer steps.

**Comment by celinelatulipe** [comment]
Yeah, this was in the original FOPP book and my students struggle with it too. I'm thinking of just getting rid of it. But if you want to propose a smaller example, I'd consider modifying it.

**Comment by bnmnetp** [comment]
I know students struggle with it.  The data shows that clearly.  But, 

1. This is a formative exercise...
2. This is a good exercise to talk them through.
3. It is more about paying attention to the details

The question says you are the point of evaluating the expression so there should be no confusion about when the function name is first looked up.

There are also clues in the wording to help with the ordering.

Maybe a simpler one before this would be good so there is an easier one for them to get the idea and then a harder one to challenge them.

**Comment by pearcej** [comment]
I do think a simpler one would be beneficial. Maybe building from the smaller example that bmiller added right before it?

**Comment by celinelatulipe** [comment]
I added a totally different example before this one. Hopefully it helps.
